name: Blender Add-On CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install Blender
        run: |
          sudo snap install blender --classic

      - name: Install Blender Modules
        run: |
          PYTHON_BIN="/opt/hostedtoolcache/Python/3.7.17/x64"
          ls -la "$PYTHON_BIN"
          "$PYTHON_BIN" -m ensurepip --upgrade
          "$PYTHON_BIN" -m pip install opencv-python mediapipe
          "$PYTHON_BIN" -m pip list
