name: Blender Add-On CI

on: [push, pull_request]

jobs:
  blender-job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Install System Python Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install numpy opencv-python-headless mediapipe

    - name: Download and Install Blender
      run: |
        BLENDER_VERSION="blender-3.2.0-linux-x64"
        wget https://download.blender.org/release/Blender3.2/${BLENDER_VERSION}.tar.xz
        tar -xf ${BLENDER_VERSION}.tar.xz
        sudo mv ${BLENDER_VERSION} /opt/blender
        echo "PATH=/opt/blender:$PATH" >> $GITHUB_ENV

    - name: Debug Python and Pip Versions
      run: |
        python3 --version
        pip3 --version

    - name: Copy Add-On to Blender's Add-On Directory
      run: |
        ADDON_DIR="/opt/blender/3.2/scripts/addons"
        mkdir -p $ADDON_DIR/BlendArMocap
        cp -r . $ADDON_DIR/BlendArMocap
        echo "Copied Add-On to $ADDON_DIR/BlendArMocap"

    - name: Enable Add-On and Run Tests
      run: |
        /opt/blender/blender --background --python src/cgt_tests/test_cgt_math.py  -- --verbose --testdir src/cgt_tests/

