name: Blender Add-On CI

on: [push, pull_request]

jobs:
  blender-job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Define Add-On Directory
      run: echo "ADDON_DIR=/usr/share/blender/scripts/add_ons" >> $GITHUB_ENV

    - name: Copy Add-On to Blender's Add-On Directory
      run: |
        mkdir -p $ADDON_DIR
        mkdir -p $ADDON_DIR/BlendArMocap
        cp -r . $ADDON_DIR/BlendArMocap
        which python
        whereis python
        which pip
        whereis pip
    
    - name: Install Blender
      run: |
        sudo apt-get update
        sudo apt-get install -y blender

    - name: Install Dependencies with Blender's Python
      run: blender -b --python install_deps.py

    - name: Enable Add-On and Run Tests
      run: |
        which blender
        whereis blender
        ls -la  /usr/share/blender/scripts
        ls -la  /usr/share/blender
        blender -b --python src/cgt_tests/test_cgt_math.py      
        
# --python-expr "import bpy; bpy.ops.preferences.addon_enable(module='BlendArMocap'); bpy.ops.wm.save_userpref()"


# jobs: #bpy.ops.preferences.addon_enable(module='BlendArMocap')
#   test:
#     runs-on: ubuntu-latest
#     container: linuxserver/blender:4.1.0
#     steps:
#       - uses: actions/checkout@v2
#       - name: Run Blender Operations
#         run: |
#           blender/4.1/python/bin/python3.11 -m pip install opencv-python mediapipe
#           ls -la

#       - name: Define Add-On Directory
#         run: echo "ADDON_DIR=$HOME/.config/blender/4.1/scripts/addons" >> $GITHUB_ENV

#       - name: Copy Add-On to Blender's Add-On Directory
#         run: |
#           mkdir -p $ADDON_DIR
#           mkdir -p $ADDON_DIR/BlendArMocap
#           cp -r . $ADDON_DIR/BlendArMocap

#       - name: Enable Add-On and Run Tests
#         run: |
#           blender -b --python-expr "import bpy; bpy.ops.preferences.addon_enable(module='BlendArMocap'); bpy.ops.wm.save_userpref()" --python src/cgt_tests/test_cgt_math.py      
      
      # # - name: Set up Python
      # #   uses: actions/setup-python@v2
      # #   with:
      # #     python-version: '3.7'

      # - name: Install Blender
      #   run: |
      #     sudo snap install blender --classic
      #     which blender
      #     ls -la /snap/bin/blender
      #     echo "Python in snap?"
      #     ls -la /snap/bin
      #     echo "Python share"
      #     ls -la /usr/share

      # - name: Install Blender Modules
      #   run: |
      #     PYTHON_BIN="/opt/hostedtoolcache/Python/3.7.17/x64/python"
      #     PYTHON_DIR="/opt/hostedtoolcache/Python/3.7.17/x64"
      #     ls -la "$PYTHON_DIR"
      #     "$PYTHON_BIN" -m ensurepip --upgrade
      #     "$PYTHON_BIN" -m pip install opencv-python mediapipe
      #     "$PYTHON_BIN" -m pip list

